---
title: "xYAF: A metric to evaluate punt returns in the NFL"
author: "Ethan, Kilbourne, Michael"
date: "12/7/2021"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(dplyr)
library(GGally)
library(ISLR)
library(caret)
library(MASS)
library(class)
library(knitr)
library(leaps)
library(glmnet)
library(boot)
library(gam)
library(tree)
library(gbm)
library(randomForest)
library(e1071)

```

# Introduction

## Background - "Expected" metrics

- In sports analytics, "expected" metrics are used to evaluate player or team performance
  - Soccer: Expected goals (xG) $^{[1]}$, expected assists, expected points
  - Basketball: Expected points, expected possession value $^{[2]}$
  - Football: Expected Yards after Catch $^{[3]}$
  
- Many uses for these metrics
  - Compare a player's output to an objective baseline
  - Evaluate a team's performance by eliminating randomness
  
## Expected Yards After Fielding (xYAF)

- Given the current conditions when fielding a punt, how many yards do we expect the punt returner to gain

- Takes into account
  - Punt position
  - Fielding position
  - All defender positions (relative)
  - Punt hang time
  
- Should return an accurate estimate of how many yards the player gains based on these factors

## Data

- NFL 2022 Big Data Bowl
  - "The annual sports analytics contest from NFL Football Operations challenges members of the analytics community to contribute to the NFL’s continuing evolution of the use of advanced analytics."
  - Last year's winner: "A Defensive Player Coverage Evaluation Framework"$^{[3]}$
  - This year, focuses on Special Teams Plays
  - Contains 19,979 plays from 2018 to 2020
  
- After filtering, we predict based on ~2000 returned punts


# Model Set 1 - Mikey

## slide

text here

# Model Set 2 - Kilbourne

## slide 

text here

# Evaluation and Conclusion

## Model Uses

text here

## Examples



## Works Cited

[1] Sam Green. Assessing the performance of Premier League goalscorers. Stats
Perform, 2012.

[2] https://grantland.com/features/expected-value-possession-nba-analytics/

[3] https://www.nfl.com/news/next-gen-stats-intro-to-expected-yards-after-catch-0ap3000000983644

[4] Peng et. al., A Defensive Player Coverage Evaluation Framework, https://www.kaggle.com/model284/a-defensive-player-coverage-evaluation-framework
